####################################################################
# VSTS Build Configuration, Version 1.4
#
# (c)2022 superdev GmbH
####################################################################

name: $[format('{0}', variables['buildName'])]

pool:
  vmImage: 'windows-2019'

trigger:
  branches:
    include:
    - master
    - develop
    - feature/*
    - bugfix/*

  paths:
    exclude:
    - README.md
    - Images/*
    - Samples/*

variables:
  solution: 'PushNotifications.Server.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  majorVersion: 1
  minorVersion: 3
  patchVersion: $[counter(format('{0}.{1}', variables.majorVersion, variables.minorVersion), 0)]
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    # Versioning: 1.0.0
    semVersion: $[format('{0}.{1}.{2}', variables.majorVersion, variables.minorVersion, variables.patchVersion)]
  ${{ if and(ne(variables['Build.SourceBranch'], 'refs/heads/master'), not(startsWith(variables['Build.SourceBranch'], 'refs/pull/'))) }}:
    # Versioning: 1.0.0-pre
    semVersion: $[format('{0}.{1}.{2}-pre', variables.majorVersion, variables.minorVersion, variables.patchVersion)]
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/pull/') }}:
    # Versioning: 1.0.0-pr.000000001
    semVersion: $[format('{0}.{1}.{2}-pr.{3}', variables.majorVersion, variables.minorVersion, variables.patchVersion, variables['System.PullRequest.PullRequestId'])]
  buildName: $[format('{0}', variables.semVersion)]

steps:
- task: Bash@3
  displayName: 'Print all variables'
  inputs:
    targetType: 'inline'
    script: 'env | sort'
   
- task: Assembly-Info-NetCore@2
  displayName: 'Update Assembly Info'
  inputs:
    Path: '$(Build.SourcesDirectory)'
    FileNames: |
      **/*.csproj
    InsertAttributes: true
    FileEncoding: 'auto'
    WriteBOM: false
    Product: 'PushNotifications.Server'
    Description: ''
    Company: 'superdev GmbH'
    Copyright: '(c) $(date:YYYY) superdev GmbH'
    VersionNumber: '$(Build.BuildNumber)'
    FileVersionNumber: '$(Build.BuildNumber)'
    InformationalVersion: '$(Build.BuildNumber)'
    PackageVersion: '$(Build.BuildNumber)'
    LogLevel: 'verbose'
    FailOnWarning: false
    DisableTelemetry: false'


- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 5.x'
  inputs:
    versionSpec: 5.x

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: '$(solution)'
    msbuildArgs: ''
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DownloadSecureFile@1
  name: AuthKey_QWWBGJLG7F
  displayName: 'Download AuthKey'
  inputs:
    secureFile: 'AuthKey_QWWBGJLG7F.p8'
   
- task: DownloadSecureFile@1
  name: ServiceAccountKeyFile
  displayName: 'Download ServiceAccountKeyFile'
  inputs:
    secureFile: 'ServiceAccountKeyFile.json'
   
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: |
      AuthKey_QWWBGJLG7F.p8
      ServiceAccountKeyFile.json
    TargetFolder: '$(System.DefaultWorkingDirectory)/Tests/PushNotifications.Server.Tests/bin/Release/net5.0/Testdata'
    OverWrite: true
    flattenFolders: true

- task: DotNetCoreCLI@2
  displayName: 'Run UnitTests'
  inputs:
    command: test
    projects: '**/*.Tests.csproj'
    arguments: '--no-restore --no-build --configuration $(buildConfiguration) /p:CollectCoverage=true /p:Exclude="[Microsoft*]*%2C[Mono*]*%2C[xunit*]*%2C[*.Testdata]*" /p:CoverletOutput=UnitTests.coverage.cobertura.xml /p:MergeWith=$(Build.SourcesDirectory)/Tests/CoverletOutput/coverage.json /p:CoverletOutputFormat=cobertura'
    
- task: Palmmedia.reportgenerator.reportgenerator-build-release-task.reportgenerator@4
  displayName: 'Create Code Coverage Report'
  inputs:
    reports: '$(Build.SourcesDirectory)/Tests/**/*.coverage.cobertura.xml'
    targetdir: '$(Build.SourcesDirectory)/CodeCoverage'
    reporttypes: 'Cobertura'
    assemblyfilters: '-xunit*'
    
- task: DotNetCoreCLI@2
  displayName: 'Pack PushNotifications.Server'
  inputs:
    command: pack
    packagesToPack: PushNotifications.Server/PushNotifications.Server.csproj
    versioningScheme: byEnvVar
    versionEnvVar: semVersion
    
- task: DotNetCoreCLI@2
  displayName: 'Pack PushNotifications.Server.AspNetCore'
  inputs:
    command: pack
    packagesToPack: PushNotifications.Server.AspNetCore/PushNotifications.Server.AspNetCore.csproj
    versioningScheme: byEnvVar
    versionEnvVar: semVersion

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'

    Contents: |
     **\bin\$(buildConfiguration)\**
     **\bin\*.nupkg

    TargetFolder: '$(Build.ArtifactStagingDirectory)'
     
- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Build.SourcesDirectory)/CodeCoverage/Cobertura.xml'
    reportDirectory: '$(Build.SourcesDirectory)/CodeCoverage'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
